/** Prism AI — Registro de proveedores (BYOK: trae tu propia clave) */
import type { ProviderDef, ProviderId } from "./types";

export const PROVIDERS: ProviderDef[] = [
  {
    id: "aihubmix",
    name: "AiHubMix",
    tagline: "Una clave para todo · Kimi K3 gratis y 27+ modelos -free",
    protocol: "openai",
    baseUrl: "https://aihubmix.com/v1",
    keyUrl: "https://aihubmix.com/apikey",
    docsUrl: "https://doc.aihubmix.com/",
    defaultModels: [
      "coding-kimi-k3-free",
      "gpt-5.5-free",
      "gpt-4.1-free",
      "gpt-4.1-mini-free",
      "gpt-4.1-nano-free",
      "gpt-4o-free",
      "gemini-3-flash-preview-free",
      "glm-4.7-flash-free",
      "deepseek-v3-free",
      "ling-2.6-flash-free",
      "step-3.5-flash-free",
      "xiaomi-mimo-v2.5-free",
    ],
    color: "#8B5CF6",
    featured: true,
  },
  {
    id: "openai",
    name: "OpenAI",
    tagline: "GPT-5, GPT-4.1, o4-mini · sin capa gratuita",
    protocol: "openai",
    baseUrl: "https://api.openai.com/v1",
    keyUrl: "https://platform.openai.com/api-keys",
    defaultModels: ["gpt-4o", "gpt-4.1", "gpt-4.1-mini", "gpt-5", "gpt-5-mini", "o3", "o4-mini"],
    color: "#10A37F",
  },
  {
    id: "anthropic",
    name: "Anthropic",
    tagline: "Claude Opus, Sonnet y Haiku",
    protocol: "anthropic",
    baseUrl: "https://api.anthropic.com",
    keyUrl: "https://console.anthropic.com/settings/keys",
    defaultModels: [
      "claude-sonnet-4-5-20250929",
      "claude-opus-4-1-20250805",
      "claude-3-7-sonnet-20250219",
      "claude-3-5-haiku-20241022",
    ],
    color: "#D97757",
  },
  {
    id: "gemini",
    name: "Google Gemini",
    tagline: "Capa gratuita generosa · Gemini Flash incluido",
    protocol: "gemini",
    baseUrl: "https://generativelanguage.googleapis.com/v1beta",
    keyUrl: "https://aistudio.google.com/app/apikey",
    defaultModels: ["gemini-2.5-pro", "gemini-2.5-flash", "gemini-2.5-flash-lite"],
    color: "#4285F4",
  },
  {
    id: "deepseek",
    name: "DeepSeek",
    tagline: "Chat y Reasoner, precio imbatible",
    protocol: "openai",
    baseUrl: "https://api.deepseek.com/v1",
    keyUrl: "https://platform.deepseek.com/api_keys",
    defaultModels: ["deepseek-chat", "deepseek-reasoner"],
    color: "#4D6BFE",
  },
  {
    id: "openrouter",
    name: "OpenRouter",
    tagline: "Cientos de modelos · decenas gratis con :free",
    protocol: "openai",
    baseUrl: "https://openrouter.ai/api/v1",
    keyUrl: "https://openrouter.ai/keys",
    defaultModels: [
      "deepseek/deepseek-chat-v3-0324:free",
      "meta-llama/llama-3.3-70b-instruct:free",
      "google/gemini-2.0-flash-exp:free",
      "qwen/qwen3-coder:free",
      "z-ai/glm-4.5-air:free",
    ],
    color: "#6467F2",
  },
  {
    id: "groq",
    name: "Groq",
    tagline: "Inferencia ultrarrápida · capa gratuita generosa",
    protocol: "openai",
    baseUrl: "https://api.groq.com/openai/v1",
    keyUrl: "https://console.groq.com/keys",
    defaultModels: [
      "llama-3.3-70b-versatile",
      "llama-3.1-8b-instant",
      "qwen/qwen3-32b",
      "moonshotai/kimi-k2-instruct",
    ],
    color: "#F55036",
  },
  {
    id: "xai",
    name: "xAI",
    tagline: "Grok con información en tiempo real",
    protocol: "openai",
    baseUrl: "https://api.x.ai/v1",
    keyUrl: "https://console.x.ai",
    defaultModels: ["grok-4", "grok-3", "grok-3-mini"],
    color: "#FFFFFF",
  },
  {
    id: "zai",
    name: "GLM · Z.ai",
    tagline: "GLM-Flash gratis y superación de código",
    protocol: "openai",
    baseUrl: "https://api.z.ai/api/paas/v4",
    keyUrl: "https://z.ai/manage-apikey/apikey-list",
    defaultModels: ["glm-4.5-flash", "glm-4.6", "glm-4.5-air"],
    color: "#3B82F6",
  },
  {
    id: "ollama",
    name: "Ollama (local)",
    tagline: "Modelos locales en tu equipo, sin coste",
    protocol: "openai",
    baseUrl: "http://localhost:11434/v1",
    defaultModels: ["llama3.2", "qwen2.5", "mistral"],
    color: "#A3A3A3",
    directByDefault: true,
  },
  {
    id: "custom",
    name: "Personalizado",
    tagline: "Cualquier API compatible con OpenAI",
    protocol: "openai",
    baseUrl: "https://",
    defaultModels: [],
    color: "#F472B6",
  },
];

export const PROVIDER_MAP: Record<ProviderId, ProviderDef> = Object.fromEntries(
  PROVIDERS.map((p) => [p.id, p])
) as Record<ProviderId, ProviderDef>;

export function getProvider(id: ProviderId): ProviderDef {
  return PROVIDER_MAP[id];
}
