/** Prism AI — Registro de proveedores (BYOK: trae tu propia clave) */
import type { ProviderDef, ProviderId } from "./types";

export const PROVIDERS: ProviderDef[] = [
  {
    id: "aihubmix",
    name: "AiHubMix",
    tagline: "Una clave para todo · Kimi K3 gratis y 27+ modelos -free",
    protocol: "openai",
    baseUrl: "https://aihubmix.com/v1",
    keyUrl: "https://aihubmix.com/apikey",
    docsUrl: "https://doc.aihubmix.com/",
    defaultModels: [
      "coding-kimi-k3-free",
      "gpt-5.5-free",
      "gpt-4.1-free",
      "gpt-4.1-mini-free",
      "gpt-4.1-nano-free",
      "gpt-4o-free",
      "gemini-3-flash-preview-free",
      "glm-4.7-flash-free",
      "deepseek-v3-free",
      "ling-2.6-flash-free",
      "step-3.5-flash-free",
      "xiaomi-mimo-v2.5-free",
    ],
    color: "#8B5CF6",
    featured: true,
  },
  {
    id: "kimi",
    name: "Kimi · Moonshot",
    tagline: "API oficial · Kimi K3 y K2 · crédito de prueba al registrarte",
    protocol: "openai",
    baseUrl: "https://api.moonshot.ai/v1",
    keyUrl: "https://platform.moonshot.ai/console/api-keys",
    docsUrl: "https://platform.moonshot.ai/docs",
    hint: "Pega la clave de platform.moonshot.ai. En China cambia la URL a https://api.moonshot.cn/v1.",
    defaultModels: [
      "kimi-k3",
      "kimi-k3-preview",
      "kimi-k2-0905-preview",
      "kimi-k2-turbo-preview",
      "moonshot-v1-128k",
      "moonshot-v1-32k",
    ],
    color: "#2563EB",
  },
  {
    id: "nvidia",
    name: "NVIDIA NIM",
    tagline: "Kimi K3, DeepSeek R1, Gemma · créditos al crear la cuenta",
    protocol: "openai",
    baseUrl: "https://integrate.api.nvidia.com/v1",
    keyUrl: "https://build.nvidia.com/settings/api-keys",
    docsUrl: "https://docs.api.nvidia.com",
    hint: "Clave nvapi-… de build.nvidia.com. El id es el de la ficha (org/nombre, ej. moonshotai/kimi-k3). También vale pegar la URL o el snippet Python de Build.",
    defaultModels: [
      "moonshotai/kimi-k3",
      "deepseek-ai/deepseek-r1",
      "google/gemma-2-27b-it",
      "qwen/qwen2.5-72b-instruct",
    ],
    color: "#76B900",
  },
  {
    id: "openai",
    name: "OpenAI",
    tagline: "GPT-5, GPT-4.1, o4-mini · sin capa gratuita",
    protocol: "openai",
    baseUrl: "https://api.openai.com/v1",
    keyUrl: "https://platform.openai.com/api-keys",
    defaultModels: ["gpt-4o", "gpt-4.1", "gpt-4.1-mini", "gpt-5", "gpt-5-mini", "o3", "o4-mini"],
    color: "#10A37F",
  },
  {
    id: "anthropic",
    name: "Anthropic",
    tagline: "Claude Opus, Sonnet y Haiku",
    protocol: "anthropic",
    baseUrl: "https://api.anthropic.com",
    keyUrl: "https://console.anthropic.com/settings/keys",
    defaultModels: [
      "claude-sonnet-4-5-20250929",
      "claude-opus-4-1-20250805",
      "claude-3-7-sonnet-20250219",
      "claude-3-5-haiku-20241022",
    ],
    color: "#D97757",
  },
  {
    id: "gemini",
    name: "Google Gemini",
    tagline: "Capa gratuita generosa · Gemini Flash incluido",
    protocol: "gemini",
    baseUrl: "https://generativelanguage.googleapis.com/v1beta",
    keyUrl: "https://aistudio.google.com/app/apikey",
    // Punto de partida cuando aún no se ha pulsado «Actualizar modelos», que es
    // lo que pregunta a Google por la lista real. Comprobado en agosto de 2026;
    // la serie 2.5 se quedó atrás y no aparecía nada de la 3.x.
    defaultModels: [
      "gemini-3.7-flash",
      "gemini-3.6-flash",
      "gemini-3.5-flash-lite",
      "gemini-3.1-flash-lite",
      "gemini-3.1-pro-preview",
    ],
    color: "#4285F4",
  },
  {
    id: "deepseek",
    name: "DeepSeek",
    tagline: "Chat y Reasoner, precio imbatible",
    protocol: "openai",
    baseUrl: "https://api.deepseek.com/v1",
    keyUrl: "https://platform.deepseek.com/api_keys",
    defaultModels: ["deepseek-chat", "deepseek-reasoner"],
    color: "#4D6BFE",
  },
  {
    id: "openrouter",
    name: "OpenRouter",
    tagline: "Cientos de modelos · decenas gratis con :free",
    protocol: "openai",
    baseUrl: "https://openrouter.ai/api/v1",
    keyUrl: "https://openrouter.ai/keys",
    defaultModels: [
      "deepseek/deepseek-chat-v3-0324:free",
      "meta-llama/llama-3.3-70b-instruct:free",
      "google/gemini-2.0-flash-exp:free",
      "qwen/qwen3-coder:free",
      "z-ai/glm-4.5-air:free",
    ],
    color: "#6467F2",
  },
  {
    id: "tokenrouter",
    name: "TokenRouter",
    tagline: "Un endpoint para varios proveedores · modelos con «-free»",
    protocol: "openai",
    baseUrl: "https://api.tokenrouter.com/v1",
    keyUrl: "https://www.tokenrouter.com/",
    docsUrl: "https://www.tokenrouter.com/models/",
    hint: "Pega el snippet OpenAI (base_url + api_key + model). También vale tokenrouter.me o api.tokenrouter.io.",
    // Punto de partida: la lista real se trae con «Modelos» en Ajustes, que es
    // lo único fiable — el catálogo de un router cambia cada pocas semanas.
    defaultModels: [
      "z-ai/glm-5.3-free",
      "deepseek/deepseek-v4-pro-0813-free",
      "qwen/qwen3.8-max-free",
    ],
    color: "#22D3EE",
  },
  {
    id: "groq",
    name: "Groq",
    tagline: "Inferencia ultrarrápida · capa gratuita generosa",
    protocol: "openai",
    baseUrl: "https://api.groq.com/openai/v1",
    keyUrl: "https://console.groq.com/keys",
    defaultModels: [
      "llama-3.3-70b-versatile",
      "llama-3.1-8b-instant",
      "qwen/qwen3-32b",
      "moonshotai/kimi-k2-instruct",
    ],
    color: "#F55036",
  },
  {
    id: "cerebras",
    name: "Cerebras",
    tagline: "El free tier más rápido · Llama, Qwen y GPT-OSS",
    protocol: "openai",
    baseUrl: "https://api.cerebras.ai/v1",
    keyUrl: "https://cloud.cerebras.ai",
    docsUrl: "https://inference-docs.cerebras.ai",
    hint: "Capa gratuita permanente. Crea la clave en cloud.cerebras.ai.",
    defaultModels: [
      "llama3.3-70b",
      "llama-4-scout-17b-16e-instruct",
      "qwen-3-32b",
      "gpt-oss-120b",
    ],
    color: "#F15A24",
  },
  {
    id: "mistral",
    name: "Mistral",
    tagline: "La Plateforme · Small, Nemo y Codestral con plan experimental",
    protocol: "openai",
    baseUrl: "https://api.mistral.ai/v1",
    keyUrl: "https://console.mistral.ai/api-keys",
    docsUrl: "https://docs.mistral.ai",
    hint: "Plan experimental gratis: 1 req/s · 500 req/día. Clave en console.mistral.ai.",
    defaultModels: [
      "mistral-small-latest",
      "mistral-nemo",
      "codestral-latest",
      "open-mistral-nemo",
      "pixtral-12b-2409",
    ],
    color: "#FF8205",
  },
  {
    id: "xai",
    name: "xAI",
    tagline: "Grok con información en tiempo real",
    protocol: "openai",
    baseUrl: "https://api.x.ai/v1",
    keyUrl: "https://console.x.ai",
    defaultModels: ["grok-4", "grok-3", "grok-3-mini"],
    color: "#FFFFFF",
  },
  {
    id: "zai",
    name: "GLM · Z.ai",
    tagline: "GLM-Flash gratis y superación de código",
    protocol: "openai",
    baseUrl: "https://api.z.ai/api/paas/v4",
    keyUrl: "https://z.ai/manage-apikey/apikey-list",
    defaultModels: ["glm-4.5-flash", "glm-4.6", "glm-4.5-air"],
    color: "#3B82F6",
  },
  {
    id: "ollama",
    name: "Ollama (local)",
    tagline: "Modelos locales en tu equipo, sin coste",
    protocol: "openai",
    baseUrl: "http://localhost:11434/v1",
    defaultModels: ["llama3.2", "qwen2.5", "mistral"],
    color: "#A3A3A3",
    directByDefault: true,
    keyless: true,
    hint: "Ejecuta Ollama en este equipo y permite el origen: OLLAMA_ORIGINS=*",
  },
  {
    id: "lmstudio",
    name: "LM Studio (local)",
    tagline: "Servidor local de LM Studio, compatible OpenAI",
    protocol: "openai",
    baseUrl: "http://localhost:1234/v1",
    defaultModels: [],
    color: "#9855FF",
    directByDefault: true,
    keyless: true,
    docsUrl: "https://lmstudio.ai/",
  },
  /* ---------- runtimes locales ----------
   *
   * Mismo patrón que LM Studio, y por el mismo motivo: `defaultModels: []`.
   * A un servidor local no se le adivina qué modelos tiene descargados — se
   * le pregunta con «Probar». Escribir aquí una lista de nombres sería
   * repetir el fallo de los sugeridos de OpenRouter: proponer modelos que no
   * existen en TU máquina.
   *
   * El puerto es el que trae cada proyecto de fábrica; si lo cambiaste, se
   * edita la URL base y ya. */
  {
    id: "llamacpp",
    name: "llama.cpp (local)",
    tagline: "El motor sobre el que corre casi todo lo demás",
    protocol: "openai",
    baseUrl: "http://localhost:8080/v1",
    defaultModels: [],
    color: "#E8A33D",
    directByDefault: true,
    keyless: true,
    hint: "Arranca el servidor: llama-server -m modelo.gguf --port 8080",
    docsUrl: "https://github.com/ggml-org/llama.cpp",
  },
  {
    id: "jan",
    name: "Jan (local)",
    tagline: "Alternativa libre a ChatGPT, 100% sin conexión",
    protocol: "openai",
    baseUrl: "http://localhost:1337/v1",
    defaultModels: [],
    color: "#4F46E5",
    directByDefault: true,
    keyless: true,
    hint: "Activa el servidor local en Jan (Settings → Local API Server).",
    docsUrl: "https://jan.ai",
  },
  {
    id: "vllm",
    name: "vLLM (local)",
    tagline: "Motor de producción para tu propia GPU",
    protocol: "openai",
    baseUrl: "http://localhost:8000/v1",
    defaultModels: [],
    color: "#22C55E",
    directByDefault: true,
    keyless: true,
    hint: "vllm serve <modelo> levanta la API compatible en el puerto 8000.",
    docsUrl: "https://docs.vllm.ai",
  },
  {
    id: "mlx",
    name: "MLX (local, Mac)",
    tagline: "Lo más rápido en un Mac con chip M",
    protocol: "openai",
    baseUrl: "http://localhost:8080/v1",
    defaultModels: [],
    color: "#0EA5E9",
    directByDefault: true,
    keyless: true,
    hint: "mlx_lm.server levanta la API compatible. Solo en Mac Apple Silicon.",
    docsUrl: "https://github.com/ml-explore/mlx",
  },
  {
    id: "llamafile",
    name: "llamafile (local)",
    tagline: "Un solo archivo que es modelo y servidor a la vez",
    protocol: "openai",
    baseUrl: "http://localhost:8080/v1",
    defaultModels: [],
    color: "#F97316",
    directByDefault: true,
    keyless: true,
    hint: "Descargas el .llamafile, le das permisos y lo ejecutas. Sin instalar nada.",
    docsUrl: "https://github.com/Mozilla-Ocho/llamafile",
  },
  {
    id: "custom",
    name: "Personalizado",
    tagline: "Cualquier API compatible con OpenAI",
    protocol: "openai",
    baseUrl: "https://",
    defaultModels: [],
    color: "#F472B6",
    hint: "Pega la URL base (…/v1) y la clave de cualquier proveedor OpenAI-compatible.",
  },
];

export const PROVIDER_MAP: Record<ProviderId, ProviderDef> = Object.fromEntries(
  PROVIDERS.map((p) => [p.id, p])
) as Record<ProviderId, ProviderDef>;

export function getProvider(id: ProviderId): ProviderDef {
  return PROVIDER_MAP[id];
}
